UI For Counters Settings & Improvements
KotRikD/tosu pull request #120
Opened 2024-04-10 22:42 UTC by cyperdark

2024-04-15 13:35 UTC, KotRikD requested changes

2024-04-15 13:35 UTC, KotRikD commented on packages/server/router/index.ts
> +                const staticPath =
Я уже знаешь насчёт чего думаю, может вынести эту хрень в хелпер? Типо я вижу уже несколько десятков мест, где используется подобный синтаксис

2024-04-15 13:35 UTC, KotRikD commented on packages/server/router/index.ts
> +                const staticPath =
+1

2024-04-15 13:35 UTC, KotRikD commented on packages/server/utils/counters.ts
> +            key === null ||
typescript считает всё false, что null/undefined, попробуй напрямую делать проверку аля !key, !value

2024-04-15 13:35 UTC, KotRikD commented on packages/server/utils/counters.ts
> +        | {
тип лучше вынести в отдельный файл, возможно типо `./counters.types.ts`, и сделать там `ISettings` или чо-нибудь такое

2024-04-15 13:35 UTC, KotRikD commented on packages/server/utils/counters.ts
> +        | {
потому что есть подозрения, что будем переиспользовать

2024-04-15 13:35 UTC, KotRikD commented on packages/server/utils/counters.ts
> +                    : item.resolution?.[0]?.toString()
Не боишься, что отстрелит потом?

2024-04-15 13:35 UTC, KotRikD commented on packages/server/utils/http.ts
> +            if (config.openDashboardOnStartup === true) {
Блин, вот любишь же ты такое, я блин правило в eslint добавлю, которое будет тебя бить за подобные вещи. Если у нас этот тип уже булевый, можно просто использовать `if (config.openDashboardOnStartup)` или тоже самое с отрицанием `if (!config.openDashboardOnStartup)`.

2024-04-15 13:35 UTC, KotRikD commented on packages/tosu/src/index.ts
> +        ((update !== null && update === true) ||
ааааааа, страшно

2024-04-23 04:32 UTC, cyperdark commented on packages/server/utils/counters.ts
> +                    : item.resolution?.[0]?.toString()
сделал заплатку
![image](https://github.com/KotRikD/tosu/assets/21735205/53aa5105-c2ed-4d65-8c45-670bffd5e5ae)

2024-04-23 04:34 UTC, cyperdark commented on packages/server/utils/http.ts
> +            if (config.openDashboardOnStartup === true) {
ага а потом какой нибудь умный человек поставит туда 1, и это будет считаться за true

2024-04-23 04:34 UTC, cyperdark commented on packages/server/utils/http.ts
> +            if (config.openDashboardOnStartup === true) {
или такое же с нулём

2024-04-23 04:37 UTC, cyperdark commented on packages/tosu/src/index.ts
> +        ((update !== null && update === true) ||
лучше? 
![image](https://github.com/KotRikD/tosu/assets/21735205/7652065d-fcb6-445c-a721-66d5e0e9cea1)

2024-04-23 05:38 UTC, cyperdark commented
https://github.com/KotRikD/tosu/pull/120/commits/595c8110c366678cae9cdb7bfad187ed580417a9 needed to request settings with in counter, even if it's opened from local file

*p.s. previous usecase required to open counter from http://127.0.0.1:24050/overlay/test, otherwise settings wont work*

2024-04-23 05:43 UTC, cyperdark commented on packages/server/utils/counters.ts
> +            key === null ||
тоже самое и для 0 или ""

2024-04-23 14:07 UTC, KotRikD approved these changes

2024-04-23 14:07 UTC, KotRikD commented on packages/server/assets/homepage.js
> +        json.error = JSON.stringify(json.error);
Если ты из-за этого сделал json летом, то можешь возвращать) Ты можешь редактировать проперти объекта, но не сам объект)

2024-04-23 14:07 UTC, KotRikD commented on packages/server/assets/homepage.js
> +  let json = await download.json();
мяу

2024-04-23 14:07 UTC, KotRikD commented on packages/server/assets/homepage.js
> +  let json = await download.json();
мяу

2024-04-23 14:07 UTC, KotRikD commented on packages/server/assets/homepage.js
> +  let json = await request.json();
мяу

2024-04-23 14:07 UTC, KotRikD commented on packages/server/assets/homepage.js
> +    let json = await request.json();
мяу

2024-04-23 14:15 UTC, cyperdark commented on packages/server/assets/homepage.js
> +        json.error = JSON.stringify(json.error);
)))

2024-04-30 08:13 UTC, KotRikD submitted a review, later dismissed
lgtm (except offsets for settings (discussed in dm))

2024-04-30 11:43 UTC, cyperdark commented
not yet for me

2024-05-02 14:20 UTC, KotRikD approved these changes

2024-05-03 13:19 UTC, merged