Add config reader
KotRikD/tosu pull request #63
Opened 2024-02-27 17:51 UTC by xxCherry

Fixes https://github.com/KotRikD/tosu/issues/57

2024-02-29 10:39 UTC, KotRikD requested changes

2024-02-29 10:39 UTC, KotRikD commented on packages/tosu/src/api/types/v2.ts
> +    cuttingEdge,
Почти у всех енумов конвенция использовать нейминг с большой буквы, пж сделайте красиво ;D

ReleaseStream.CuttingEdge
ReleaseStream.Stable

этцетра

2024-02-29 10:39 UTC, KotRikD commented on packages/tosu/src/api/utils/buildResultV2.ts
> +                // FIXME: i dont understand where tf you getting it from, it doesnt work in menu
Это лидерборд на карте, а не включен он или нет :)

2024-02-29 18:42 UTC, cyperdark commented on packages/tosu/src/api/utils/buildResultV2.ts
> +                // FIXME: i dont understand where tf you getting it from, it doesnt work in menu
тогда удалю

2024-03-01 15:40 UTC, KotRikD approved these changes
LGTM

2024-03-01 15:40 UTC, merged