Remove some `Async` & `While loops` + editor pp
KotRikD/tosu pull request #88
Opened 2024-03-04 18:18 UTC by cyperdark

2024-03-07 00:45 UTC, KotRikD requested changes

2024-03-07 00:45 UTC, KotRikD commented on packages/common/utils/config.ts
> +let HTTPServer: any;
не, давай без таких переменных

2024-03-07 00:45 UTC, KotRikD commented on packages/game-overlay/src/index.ts
> +enabled = true
это поле можно вообще под снос, в оверлее оно не используется

2024-03-07 00:45 UTC, KotRikD commented on packages/game-overlay/src/index.ts
> +    const parseURL = /overlayURL[ ]*=[ ]*(.*)/.exec(read);
Может стоит добавить начало, конец строки? (^, $)

2024-03-07 00:45 UTC, KotRikD commented on packages/game-overlay/src/index.ts
> +        return 'empty';
Я вот чо не пойму, зачем ты постоянно из промисов пытаешься достать вот такие значение, почему не упрощать все до `true/false` ?

2024-03-07 00:53 UTC, cyperdark commented on packages/game-overlay/src/index.ts
> +        return 'empty';
изначально было 3 стейта, по окончанию осталось два, так что сейчас уберу

2024-03-08 05:54 UTC, KotRikD requested changes

2024-03-08 05:54 UTC, KotRikD commented on packages/tosu/src/entities/BassDensityData/index.ts
> +    // FIXME
??

2024-03-08 05:54 UTC, KotRikD commented on packages/tosu/src/entities/MenuData/index.ts
> +    mp3ErrorAttempts: number = 0;
давай тогда `private mp3ErrorAttemps`

2024-03-08 06:20 UTC, KotRikD commented
«Отче наш, Иже еси на небесех! Да святится имя Твое, да приидет Царствие Твое, да будет воля Твоя, яко на небеси и на земли. Хлеб наш насущный даждь нам днесь; и остави нам долги наша, якоже и мы оставляем должником нашим; и не введи нас во искушение, но избави нас от лукаваго. Ибо Твое есть Царство и сила и слава во веки. Аминь.»

2024-03-08 06:20 UTC, merged